import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { resetLedgerOnVersionChange, runFirstRunTasks, runStartupTasks } from "../../src/first-run.mjs";
import { PLUGIN_VERSION, sessionLedgerFilename, summaryStateFilename } from "../../src/storage.mjs";

test("runStartupTasks configures statusline and removes legacy shim for existing users", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    const shim = join(home, "extensions", "copilot-cost", "extension.mjs");
    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(extensionEntrypoint, "");
    await writeFile(shim, "// Generated by copilot-cost setup v1\n");
    await writeFile(join(home, "settings.json"), JSON.stringify({ disabledSkills: ["other-skill", "ext-cost-setup"] }));

    const result = await runStartupTasks({ copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" });

    assert.deepEqual(result, { ledgerCleared: false, summaryCleared: false, statuslineConfigured: true, legacyShimRemoved: true });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.equal(settings.footer.showCustom, true);
    assert.deepEqual(settings.disabledSkills, ["other-skill"]);
    await assert.rejects(() => readFile(shim, "utf8"), { code: "ENOENT" });
});

test("runFirstRunTasks configures the statusline after first persisted workspace state", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    await writeFile(extensionEntrypoint, "");
    await writeFile(join(data, sessionLedgerFilename(PLUGIN_VERSION)), JSON.stringify({ version: 1, runtime: { workspace: {} } }));

    const result = await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.deepEqual(result, { firstRun: true, ledgerCleared: false, summaryCleared: false, statuslineConfigured: true, legacyShimRemoved: false });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.equal(settings.footer.showCustom, true);
    assert.equal(settings.statusLine.type, "command");
    assert.match(settings.statusLine.command, /^node /);
    assert.match(settings.statusLine.command, /extension\.mjs' '--statusline'/);
    assert.deepEqual(JSON.parse(await readFile(join(data, sessionLedgerFilename(PLUGIN_VERSION)), "utf8")), { version: 1, runtime: { workspace: {} } });
    assert.deepEqual(JSON.parse(await readFile(join(data, "install-state.json"), "utf8")), {
        hadStatusLine: false,
        statusLine: null,
        hadFooterShowCustom: false,
        footerShowCustom: null,
    });
});

test("runFirstRunTasks skips sessions that already have state or no persisted workspace", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));

    assert.deepEqual(await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: { totalUsd: 1 } },
        { copilotHome: home },
    ), { firstRun: false, ledgerCleared: false, summaryCleared: false, statuslineConfigured: false, legacyShimRemoved: false });
    assert.deepEqual(await runFirstRunTasks(
        { workspacePath: undefined, priorState: undefined },
        { copilotHome: home },
    ), { firstRun: false, ledgerCleared: false, summaryCleared: false, statuslineConfigured: false, legacyShimRemoved: false });

    await assert.rejects(() => readFile(join(home, "settings.json"), "utf8"), { code: "ENOENT" });
});

test("runFirstRunTasks removes the old generated user shim without touching unmanaged files", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    const shim = join(home, "extensions", "copilot-cost", "extension.mjs");
    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(extensionEntrypoint, "");
    await writeFile(shim, "// Generated by copilot-cost setup v1\n");

    const result = await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.deepEqual(result, { firstRun: true, ledgerCleared: false, summaryCleared: false, statuslineConfigured: true, legacyShimRemoved: true });
    await assert.rejects(() => readFile(shim, "utf8"), { code: "ENOENT" });

    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(shim, "// user-owned extension\n");

    const second = await runFirstRunTasks(
        { workspacePath: "/workspace-2", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.equal(second.legacyShimRemoved, false);
    assert.equal(await readFile(shim, "utf8"), "// user-owned extension\n");
});

test("resetLedgerOnVersionChange keeps ledger when version is unchanged", async () => {
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const ledger = join(data, sessionLedgerFilename("1.2.3"));
    const summary = join(data, summaryStateFilename("1.2.3"));
    await writeFile(ledger, JSON.stringify({ version: 1, sessions: { abc: { id: "abc" } } }));
    await writeFile(summary, JSON.stringify({ version: 1, liveSessions: { abc: {} } }));
    await writeFile(join(data, "lifecycle.json"), JSON.stringify({ extensionVersion: "1.2.3" }));

    const result = await resetLedgerOnVersionChange({ pluginDataDirectory: data, extensionVersion: "1.2.3" });

    assert.deepEqual(result, { ledgerCleared: false, summaryCleared: false, fromVersion: undefined, toVersion: "1.2.3" });
    assert.match(await readFile(ledger, "utf8"), /abc/);
    assert.match(await readFile(summary, "utf8"), /abc/);
});

test("resetLedgerOnVersionChange clears rebuildable caches for changed versions", async () => {
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    await writeFile(join(data, "session-ledger.json"), JSON.stringify({ version: 1, sessions: { legacy: { id: "legacy" } } }));
    await writeFile(join(data, "summary-state.json"), JSON.stringify({ version: 1, liveSessions: { legacy: {} } }));
    await writeFile(join(data, sessionLedgerFilename("1.2.2")), JSON.stringify({ version: 1, sessions: { old: { id: "old" } } }));
    await writeFile(join(data, summaryStateFilename("1.2.2")), JSON.stringify({ version: 1, liveSessions: { old: {} } }));
    await writeFile(join(data, sessionLedgerFilename("1.2.3")), JSON.stringify({ version: 1, sessions: { current: { id: "current" } } }));
    await writeFile(join(data, summaryStateFilename("1.2.3")), JSON.stringify({ version: 1, liveSessions: { current: {} } }));
    await writeFile(join(data, "settings.json"), JSON.stringify({ mode: "footer" }));
    await writeFile(join(data, "install-state.json"), JSON.stringify({ hadStatusLine: true }));
    await writeFile(join(data, "lifecycle.json"), JSON.stringify({ extensionVersion: "1.2.2" }));

    const result = await resetLedgerOnVersionChange({ pluginDataDirectory: data, extensionVersion: "1.2.3" });

    assert.deepEqual(result, { ledgerCleared: true, summaryCleared: true, fromVersion: "1.2.2", toVersion: "1.2.3" });
    await assert.rejects(() => readFile(join(data, "session-ledger.json"), "utf8"), { code: "ENOENT" });
    await assert.rejects(() => readFile(join(data, "summary-state.json"), "utf8"), { code: "ENOENT" });
    await assert.rejects(() => readFile(join(data, sessionLedgerFilename("1.2.2")), "utf8"), { code: "ENOENT" });
    await assert.rejects(() => readFile(join(data, summaryStateFilename("1.2.2")), "utf8"), { code: "ENOENT" });
    await assert.rejects(() => readFile(join(data, sessionLedgerFilename("1.2.3")), "utf8"), { code: "ENOENT" });
    await assert.rejects(() => readFile(join(data, summaryStateFilename("1.2.3")), "utf8"), { code: "ENOENT" });
    assert.deepEqual(JSON.parse(await readFile(join(data, "settings.json"), "utf8")), { mode: "footer" });
    assert.deepEqual(JSON.parse(await readFile(join(data, "install-state.json"), "utf8")), { hadStatusLine: true });
    assert.deepEqual(JSON.parse(await readFile(join(data, "lifecycle.json"), "utf8")), { extensionVersion: "1.2.3" });
});

test("resetLedgerOnVersionChange treats existing ledger without marker as upgrade", async () => {
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    await writeFile(join(data, "session-ledger.json"), JSON.stringify({ version: 1, sessions: { abc: { id: "abc" } } }));

    const result = await resetLedgerOnVersionChange({ pluginDataDirectory: data, extensionVersion: "1.2.3" });

    assert.deepEqual(result, { ledgerCleared: true, summaryCleared: false, fromVersion: undefined, toVersion: "1.2.3" });
    await assert.rejects(() => readFile(join(data, "session-ledger.json"), "utf8"), { code: "ENOENT" });
    assert.deepEqual(JSON.parse(await readFile(join(data, "lifecycle.json"), "utf8")), { extensionVersion: "1.2.3" });
});
