import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { runFirstRunTasks, runStartupTasks } from "../../src/first-run.mjs";

test("runStartupTasks configures statusline and removes legacy shim for existing users", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    const shim = join(home, "extensions", "copilot-cost", "extension.mjs");
    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(extensionEntrypoint, "");
    await writeFile(shim, "// Generated by copilot-cost setup v1\n");
    await writeFile(join(home, "settings.json"), JSON.stringify({ disabledSkills: ["other-skill", "ext-cost-setup"] }));

    const result = await runStartupTasks({ copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" });

    assert.deepEqual(result, { statuslineConfigured: true, legacyShimRemoved: true });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.equal(settings.footer.showCustom, true);
    assert.deepEqual(settings.disabledSkills, ["other-skill"]);
    await assert.rejects(() => readFile(shim, "utf8"), { code: "ENOENT" });
});

test("runFirstRunTasks configures the statusline after first persisted workspace state", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    await writeFile(extensionEntrypoint, "");

    const result = await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.deepEqual(result, { firstRun: true, statuslineConfigured: true, legacyShimRemoved: false });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.equal(settings.footer.showCustom, true);
    assert.equal(settings.statusLine.type, "command");
    assert.match(settings.statusLine.command, /^node /);
    assert.match(settings.statusLine.command, /extension\.mjs' '--statusline'/);
    assert.deepEqual(JSON.parse(await readFile(join(data, "install-state.json"), "utf8")), {
        hadStatusLine: false,
        statusLine: null,
        hadFooterShowCustom: false,
        footerShowCustom: null,
    });
});

test("runFirstRunTasks skips sessions that already have state or no persisted workspace", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));

    assert.deepEqual(await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: { totalUsd: 1 } },
        { copilotHome: home },
    ), { firstRun: false, statuslineConfigured: false, legacyShimRemoved: false });
    assert.deepEqual(await runFirstRunTasks(
        { workspacePath: undefined, priorState: undefined },
        { copilotHome: home },
    ), { firstRun: false, statuslineConfigured: false, legacyShimRemoved: false });

    await assert.rejects(() => readFile(join(home, "settings.json"), "utf8"), { code: "ENOENT" });
});

test("runFirstRunTasks removes the old generated user shim without touching unmanaged files", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const data = await mkdtemp(join(tmpdir(), "copilot-cost-data-"));
    const extensionEntrypoint = join(await mkdtemp(join(tmpdir(), "copilot-cost-extension-")), "extension.mjs");
    const shim = join(home, "extensions", "copilot-cost", "extension.mjs");
    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(extensionEntrypoint, "");
    await writeFile(shim, "// Generated by copilot-cost setup v1\n");

    const result = await runFirstRunTasks(
        { workspacePath: "/workspace", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.deepEqual(result, { firstRun: true, statuslineConfigured: true, legacyShimRemoved: true });
    await assert.rejects(() => readFile(shim, "utf8"), { code: "ENOENT" });

    await mkdir(join(home, "extensions", "copilot-cost"), { recursive: true });
    await writeFile(shim, "// user-owned extension\n");

    const second = await runFirstRunTasks(
        { workspacePath: "/workspace-2", priorState: undefined },
        { copilotHome: home, pluginDataDirectory: data, extensionEntrypoint, platform: "posix" },
    );

    assert.equal(second.legacyShimRemoved, false);
    assert.equal(await readFile(shim, "utf8"), "// user-owned extension\n");
});
