import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

import { installExtensionShim, uninstallExtensionShim } from "../../../../scripts/lib/shim.mjs";
import { configureStatusline, uninstallStatusline } from "../../../../scripts/lib/statusline.mjs";

const pluginRoot = new URL("../../../..", import.meta.url).pathname;

test("installExtensionShim writes a managed native extension wrapper", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const result = await installExtensionShim({ copilotHome: home, pluginRoot });

    assert.equal(result.changed, true);
    const shim = await readFile(join(home, ".copilot", "extensions", "copilot-cost", "extension.mjs"), "utf8").catch(() => undefined);
    assert.equal(shim, undefined);

    const configuredShim = await readFile(join(home, "extensions", "copilot-cost", "extension.mjs"), "utf8");
    assert.match(configuredShim, /Generated by copilot-cost setup v1/);
    assert.match(configuredShim, /pathToFileURL/);
});

test("configureStatusline enables custom footer and runs the bundled extension", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    const result = await configureStatusline({ copilotHome: home, pluginRoot, platform: "posix" });

    assert.equal(result.settingsChanged, true);
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.equal(settings.experimental, true);
    assert.equal(settings.footer.showCustom, true);
    assert.equal(settings.statusLine.type, "command");
    assert.match(settings.statusLine.command, /^node /);
    assert.match(settings.statusLine.command, /extensions\/copilot-cost\/extension\.mjs' '--statusline'/);
    assert.doesNotMatch(settings.statusLine.command, /copilot-cost\/statusline\.sh/);

    const payload = {
        workspace_path: await mkdtemp(join(tmpdir(), "copilot-cost-work-")),
        context_window: { current_context_tokens: 1200, displayed_context_limit: 200000 },
        ai_used: { total_nano_aiu: 0 },
    };
    const run = spawnSync(settings.statusLine.command, {
        shell: true,
        env: { ...process.env, COPILOT_HOME: home, HOME: home },
        input: JSON.stringify(payload),
        encoding: "utf8",
    });

    assert.equal(run.status, 0);
    assert.match(run.stdout.replace(/\x1b\[[0-9;]*m/g, ""), /Total £0\.00/);
});

test("configureStatusline replaces an existing statusline command", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    await writeFile(join(home, "settings.json"), JSON.stringify({
        statusLine: { type: "command", command: "printf existing" },
    }));

    await configureStatusline({ copilotHome: home, pluginRoot, platform: "posix" });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));
    assert.match(settings.statusLine.command, /extensions\/copilot-cost\/extension\.mjs' '--statusline'/);

    const run = spawnSync(settings.statusLine.command, {
        shell: true,
        env: { ...process.env, COPILOT_HOME: home, HOME: home },
        input: JSON.stringify({ workspace_path: await mkdtemp(join(tmpdir(), "copilot-cost-work-")), context_window: {}, ai_used: { total_nano_aiu: 0 } }),
        encoding: "utf8",
    });

    assert.equal(run.status, 0);
    assert.match(run.stdout.replace(/\x1b\[[0-9;]*m/g, ""), /Total £0\.00/);
});

test("managed uninstall removes the shim and restores prior statusline settings", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    await mkdir(home, { recursive: true });
    await writeFile(join(home, "settings.json"), JSON.stringify({
        statusLine: { type: "command", command: "printf existing" },
        footer: { showCustom: false, showQuota: true },
        disabledSkills: ["other-skill", "ext-cost-setup"],
    }));

    await installExtensionShim({ copilotHome: home, pluginRoot });
    await configureStatusline({ copilotHome: home, pluginRoot, platform: "posix" });

    const shim = await uninstallExtensionShim({ copilotHome: home });
    const statusline = await uninstallStatusline({ copilotHome: home });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));

    assert.equal(shim.removed, true);
    assert.equal(statusline.settingsChanged, true);
    assert.equal(statusline.statuslineSettingsChanged, true);
    assert.equal(statusline.setupSkillEnabled, true);
    assert.deepEqual(settings.statusLine, { type: "command", command: "printf existing" });
    assert.deepEqual(settings.footer, { showCustom: false, showQuota: true });
    assert.deepEqual(settings.disabledSkills, ["other-skill"]);
});

test("managed uninstall re-enables the setup skill even when no statusline is active", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    await mkdir(home, { recursive: true });
    await writeFile(join(home, "settings.json"), JSON.stringify({
        disabledSkills: ["ext-cost-setup"],
    }));

    const statusline = await uninstallStatusline({ copilotHome: home });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));

    assert.equal(statusline.settingsChanged, true);
    assert.equal(statusline.statuslineSettingsChanged, false);
    assert.equal(statusline.setupSkillEnabled, true);
    assert.equal(Object.hasOwn(settings, "disabledSkills"), false);
});

test("managed uninstall leaves unrelated disabled skills untouched", async () => {
    const home = await mkdtemp(join(tmpdir(), "copilot-cost-home-"));
    await mkdir(home, { recursive: true });
    await writeFile(join(home, "settings.json"), JSON.stringify({
        disabledSkills: ["other-skill"],
    }));

    const statusline = await uninstallStatusline({ copilotHome: home });
    const settings = JSON.parse(await readFile(join(home, "settings.json"), "utf8"));

    assert.equal(statusline.settingsChanged, false);
    assert.equal(statusline.statuslineSettingsChanged, false);
    assert.equal(statusline.setupSkillEnabled, false);
    assert.deepEqual(settings.disabledSkills, ["other-skill"]);
});
