import { existsSync, statSync } from "node:fs";
import { readdir, readFile, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const PLUGIN_NAME = "copilot-cost";
export const MARKETPLACE_NAME = "copilot-extensions";
export const EXTENSION_NAME = "copilot-cost";
export const SETUP_SKILL_NAME = "ext-cost-setup";
export const GENERATED_MARKER = "Generated by copilot-cost setup v1";

export function copilotHome(value = process.env.COPILOT_HOME) {
    return resolve(value || join(homedir(), ".copilot"));
}

export function pluginRootFromScript(importMetaUrl) {
    return resolve(dirname(fileURLToPath(importMetaUrl)), "..");
}

export function extensionEntrypoint(pluginRoot) {
    return join(pluginRoot, "extensions", EXTENSION_NAME, "extension.mjs");
}

export function userExtensionDirectory(home) {
    return join(home, "extensions", EXTENSION_NAME);
}

export function userExtensionEntrypoint(home) {
    return join(userExtensionDirectory(home), "extension.mjs");
}

export function settingsPath(home) {
    return join(home, "settings.json");
}

export function pluginDataDirectory(home) {
    return process.env.COPILOT_PLUGIN_DATA || join(home, "plugin-data", MARKETPLACE_NAME, PLUGIN_NAME);
}

export function installStatePath(home) {
    return join(pluginDataDirectory(home), "install-state.json");
}

export async function findInstalledExtension(home, fallbackRoot = process.env.COPILOT_COST_PLUGIN_ROOT) {
    const fallback = fallbackRoot ? extensionEntrypoint(fallbackRoot) : undefined;
    if (fallback && existsSync(fallback)) {
        return fallback;
    }

    const installedRoot = join(home, "installed-plugins");
    const candidates = [];
    await collectExtensionCandidates(installedRoot, candidates);
    candidates.sort(compareByMtimeDesc);
    return candidates[0]?.path;
}

export async function assertBundledExtension(pluginRoot) {
    const entrypoint = extensionEntrypoint(pluginRoot);
    try {
        const entry = await stat(entrypoint);
        if (entry.isFile()) {
            return entrypoint;
        }
    } catch (error) {
        if (error?.code !== "ENOENT") {
            throw error;
        }
    }
    throw new Error(`Could not find bundled native extension at ${entrypoint}`);
}

async function collectExtensionCandidates(root, candidates) {
    let entries;
    try {
        entries = await readdir(root, { withFileTypes: true });
    } catch (error) {
        if (error?.code === "ENOENT") {
            return;
        }
        throw error;
    }

    for (const entry of entries) {
        const path = join(root, entry.name);
        if (entry.isDirectory()) {
            await collectExtensionCandidates(path, candidates);
            continue;
        }
        if (entry.isFile() && path.endsWith(join("extensions", EXTENSION_NAME, "extension.mjs"))) {
            const pluginRoot = dirname(dirname(dirname(path)));
            if (await isCopilotCostPlugin(pluginRoot)) {
                candidates.push({ path, mtimeMs: statSync(path).mtimeMs });
            }
        }
    }
}

async function isCopilotCostPlugin(pluginRoot) {
    try {
        const manifest = JSON.parse(await readFile(join(pluginRoot, "plugin.json"), "utf8"));
        return manifest.name === PLUGIN_NAME;
    } catch {
        return false;
    }
}

function compareByMtimeDesc(left, right) {
    if (left.mtimeMs !== right.mtimeMs) {
        return right.mtimeMs - left.mtimeMs;
    }
    return left.path.localeCompare(right.path);
}
