import { copyFile, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { copilotHome as defaultCopilotHome, pluginDataDirectory as defaultPluginDataDirectory } from "./storage.mjs";

const GENERATED_MARKER = "Generated by copilot-cost setup v1";

export function defaultExtensionEntrypoint() {
    return fileURLToPath(new URL("../extension.mjs", import.meta.url));
}

export async function configureStatusline({
    copilotHome = defaultCopilotHome(),
    pluginDataDirectory = defaultPluginDataDirectory(),
    extensionEntrypoint = defaultExtensionEntrypoint(),
    platform = process.platform === "win32" ? "windows" : "posix",
} = {}) {
    await assertFile(extensionEntrypoint, "extension entrypoint");
    const settingsFile = settingsPath(copilotHome);
    const { existed, value: settings } = await readJsonc(settingsFile);
    const priorSettings = structuredClone(settings);
    const command = shellCommand(platform, "node", [extensionEntrypoint, "--statusline"]);

    settings.experimental = true;
    settings.footer = isPlainObject(settings.footer) ? settings.footer : {};
    settings.footer.showCustom = true;
    settings.statusLine = isPlainObject(settings.statusLine)
        ? { ...settings.statusLine, type: "command", command }
        : { type: "command", command };
    removeDisabledSetupSkill(settings);

    if (JSON.stringify(settings) === JSON.stringify(priorSettings)) {
        return { settingsChanged: false, statuslineConfigured: false, statusLineCommand: command };
    }

    await writeInstallState(pluginDataDirectory, priorSettings);
    await writeJsonWithBackup(settingsFile, settings, existed);
    return { settingsChanged: true, statuslineConfigured: true, statusLineCommand: command };
}

export async function uninstallStatusline({
    copilotHome = defaultCopilotHome(),
    pluginDataDirectory = defaultPluginDataDirectory(),
} = {}) {
    const settingsFile = settingsPath(copilotHome);
    const { existed, value: settings } = await readJsonc(settingsFile);
    const state = await readInstallState(pluginDataDirectory);
    let settingsChanged = false;
    let statuslineSettingsChanged = false;
    const setupSkillEnabled = removeDisabledSetupSkill(settings);

    if (isPlainObject(settings.statusLine) && isCopilotCostStatusline(settings.statusLine.command)) {
        if (state?.hadStatusLine) {
            settings.statusLine = state.statusLine;
        } else {
            delete settings.statusLine;
        }
        settingsChanged = true;
        statuslineSettingsChanged = true;
    }

    if (state && isPlainObject(settings.footer)) {
        if (state.hadFooterShowCustom) {
            settings.footer.showCustom = state.footerShowCustom;
        } else {
            delete settings.footer.showCustom;
        }
        settingsChanged = true;
        statuslineSettingsChanged = true;
    }

    settingsChanged ||= setupSkillEnabled;
    if (settingsChanged) {
        await writeJsonWithBackup(settingsFile, settings, existed);
    }
    return { settingsChanged, statuslineSettingsChanged, setupSkillEnabled };
}

export async function removeLegacyShim({ copilotHome = defaultCopilotHome() } = {}) {
    const directory = join(copilotHome, "extensions", "copilot-cost");
    const entrypoint = join(directory, "extension.mjs");
    try {
        const content = await readFile(entrypoint, "utf8");
        if (!content.includes(GENERATED_MARKER)) {
            return false;
        }
    } catch (error) {
        if (error?.code === "ENOENT") {
            return false;
        }
        throw error;
    }
    await rm(directory, { recursive: true, force: true });
    return true;
}

function settingsPath(copilotHome) {
    return join(copilotHome, "settings.json");
}

function installStatePath(pluginDataDirectory) {
    return join(pluginDataDirectory, "install-state.json");
}

async function writeInstallState(pluginDataDirectory, priorSettings) {
    const path = installStatePath(pluginDataDirectory);
    try {
        await readFile(path, "utf8");
        return;
    } catch (error) {
        if (error?.code !== "ENOENT") {
            throw error;
        }
    }
    await writeJson(path, {
        hadStatusLine: Object.hasOwn(priorSettings, "statusLine"),
        statusLine: priorSettings.statusLine ?? null,
        hadFooterShowCustom: Object.hasOwn(priorSettings.footer ?? {}, "showCustom"),
        footerShowCustom: priorSettings.footer?.showCustom ?? null,
    });
}

async function readInstallState(pluginDataDirectory) {
    try {
        return JSON.parse(await readFile(installStatePath(pluginDataDirectory), "utf8"));
    } catch (error) {
        if (error?.code === "ENOENT") {
            return undefined;
        }
        throw error;
    }
}

async function assertFile(path, label) {
    try {
        const entry = await stat(path);
        if (entry.isFile()) {
            return;
        }
    } catch (error) {
        if (error?.code !== "ENOENT") {
            throw error;
        }
    }
    throw new Error(`Could not find ${label} at ${path}`);
}

async function readJsonc(path) {
    try {
        const raw = await readFile(path, "utf8");
        if (!raw.trim()) {
            return { existed: true, value: {} };
        }
        try {
            return { existed: true, value: JSON.parse(raw) };
        } catch (jsonError) {
            try {
                return { existed: true, value: JSON.parse(stripJsonc(raw)) };
            } catch {
                throw new Error(`Could not parse ${path}: ${jsonError.message}`);
            }
        }
    } catch (error) {
        if (error?.code === "ENOENT") {
            return { existed: false, value: {} };
        }
        throw error;
    }
}

async function writeJsonWithBackup(path, value, existed) {
    await mkdir(dirname(path), { recursive: true });
    if (existed) {
        const suffix = new Date().toISOString().replace(/[:.]/g, "-");
        await copyFile(path, `${path}.bak-${suffix}`);
    }
    await writeJson(path, value);
}

async function writeJson(path, value) {
    await mkdir(dirname(path), { recursive: true });
    const temp = `${path}.${process.pid}.tmp`;
    await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`);
    await rename(temp, path);
}

function stripJsonc(input) {
    return stripTrailingCommas(stripComments(input));
}

function stripComments(input) {
    let output = "";
    let inString = false;
    let inLineComment = false;
    let inBlockComment = false;
    let escaped = false;
    for (let index = 0; index < input.length; index += 1) {
        const char = input[index];
        const next = input[index + 1];
        if (inLineComment) {
            if (char === "\n" || char === "\r") {
                inLineComment = false;
                output += char;
            }
            continue;
        }
        if (inBlockComment) {
            if (char === "*" && next === "/") {
                inBlockComment = false;
                index += 1;
            } else if (char === "\n" || char === "\r") {
                output += char;
            }
            continue;
        }
        if (inString) {
            output += char;
            if (escaped) {
                escaped = false;
            } else if (char === "\\") {
                escaped = true;
            } else if (char === "\"") {
                inString = false;
            }
            continue;
        }
        if (char === "\"") {
            inString = true;
            output += char;
        } else if (char === "/" && next === "/") {
            inLineComment = true;
            index += 1;
        } else if (char === "/" && next === "*") {
            inBlockComment = true;
            index += 1;
        } else {
            output += char;
        }
    }
    return output;
}

function stripTrailingCommas(input) {
    let output = "";
    let inString = false;
    let escaped = false;
    for (let index = 0; index < input.length; index += 1) {
        const char = input[index];
        if (inString) {
            output += char;
            if (escaped) {
                escaped = false;
            } else if (char === "\\") {
                escaped = true;
            } else if (char === "\"") {
                inString = false;
            }
            continue;
        }
        if (char === "\"") {
            inString = true;
            output += char;
            continue;
        }
        if (char === ",") {
            let nextIndex = index + 1;
            while (/\s/.test(input[nextIndex] ?? "")) {
                nextIndex += 1;
            }
            if (input[nextIndex] === "}" || input[nextIndex] === "]") {
                continue;
            }
        }
        output += char;
    }
    return output;
}

function shellCommand(platform, command, args) {
    const quote = platform === "windows" ? windowsQuote : singleQuote;
    return [command, ...args.map(quote)].join(" ");
}

function isCopilotCostStatusline(command) {
    return typeof command === "string" && /copilot-cost/i.test(command) && /statusline/i.test(command);
}

function removeDisabledSetupSkill(settings) {
    if (!Array.isArray(settings.disabledSkills)) {
        return false;
    }
    const disabledSkills = settings.disabledSkills.filter((skill) => skill !== "ext-cost-setup");
    if (disabledSkills.length === settings.disabledSkills.length) {
        return false;
    }
    if (disabledSkills.length > 0) {
        settings.disabledSkills = disabledSkills;
    } else {
        delete settings.disabledSkills;
    }
    return true;
}

function isPlainObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
}

function singleQuote(value) {
    return `'${assertNoNewlines(value).replaceAll("'", "'\\''")}'`;
}

function windowsQuote(value) {
    return `"${assertNoNewlines(value).replaceAll("\"", "\\\"")}"`;
}

function assertNoNewlines(value) {
    if (/[\r\n]/.test(value)) {
        throw new Error("Statusline commands cannot contain newlines");
    }
    return value;
}
